### ISSUE TITLE
Allow saving of stream

### ISSUE THREAD

**Issue by azrdev** [raptor2101/Mediathek#63]
I'd like to not only watch entries from the archive, but also to save them to disk for later viewing (ie. after they have been de-published).

**Comment by raptor2101** [comment]
In the first version of this plugin this was implemented but removed later for because: doing "thinks" in background isn't natively supported by kodi (as far as i understand it) so the addons have to handle threading by themselves. This leads to the akward situation that some addon-threads passing around more or less unwatched by the hosting prozess (kodi). Downloading large files takes time, so maybe the addon has to prevent closing kodi because of finishing downloading. How to handle aborted Downloads.

Even the filemanagement (delete of watched files) adds some degree of complexity because of the user interface (remotecontroll, no keyboard). i was never able to get it working in a nice way.

There are better tools to "autmaticaly download" mediathek-files (f.e MediathekView, JDownloader) who are runnable headless/batched who are perfectly doing the job you request. IMHO Doing it from inside Kodi isn't the right way ...

**Comment by Wikinaut** [comment]
@raptor2101 the youtube-dl Addon can download in the background! this is the source: https://github.com/ruuk/script.module.youtube.dl

**Comment by Wikinaut** [comment]
It takes arbitrary stream urls, not only Youtube-Urls. I use this already to download "Tatort" or so.

**Comment by raptor2101** [comment]
The addon you mentioned does exactly what i described. Starts a background thread, shipping a third party python lib and doas some lot of (awsome) magic.

The purpose of my addon is to watch videos using kodi internal functions. To "download" something you need to ship you own libraries or using OS-dependant methods/tools to archive the download. This isn't something I'am able to archive in my spare time.

Some excample: youtube-dl don't support rtmp nativly (wich is used by most german mediathekes for a unknown reason), it hand over these task to rtmpdump (wich is a frontend for librtmp). Most (linux) packages only forces librtmp as "dependecy" (most optional). Additinal some systems don't even ship librtmp (AppleTV, some closed boxes and some systems with special architecture)

In the end, if I implement a "download-option", I have to probe for rtmpdump and do some nasty os related thinks only to get a simple "download these movie" running (and yes i'am already done this ;)) Hopefully the german content provider (at least the public ones) switches to HTML5 and DRMles (direct downloadable) files. This would make thinks way more easy ...

**Comment by Wikinaut** [comment]
My idea was, that you simply 

* add a context entry (I currently don't know, how I could code this) if the youtube-dl Addon is installed
* which entry allows to "fires" the youtube-dl (yes, it can be used as an "engine to download a stream")

so that the youtube-dl records the stream.
